### PR TITLE
Make compatible with Thunderbird 60

### PR DESCRIPTION
**Pull request by matthias-g**
This makes the addon compatible with Thunderbird 60 (see https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57)

### CODE REVIEW

**Comment by richq** [comment]
Thanks! I hadn't been using it with TB60 because Wingdings started inexplicably working, and I didn't think this addon would keep working after the updates in 60.

**Comment by matthias-g** [comment]
Thanks for merging! Could you please also push it to AMO?

**Comment by richq** [comment]
I can no longer submit it to addons.mozilla.org, "legacy" extensions are no longer accepted :-(

**Comment by richq** [comment]
Ah, turns out I was in the wrong place - it's https://addons.thunderbird.net/ now! Submitted.

**Comment by matthias-g** [comment]
Thanks!

**Pull request merged**
